version: "3"

services:

  wordpress_workspace:
    depends_on:
      - wordpress_db
    image: wordpress:latest
    container_name: wordpress_workspace
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wordpress

  wordpress_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: wordpress_db
    ports:
      - "33060:3306"
    restart: unless-stopped
    volumes:
      - wordpress_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress


  drupal_workspace:
    image: drupal:9-php7.4-apache
    container_name: drupal_workspace
    ports:
      - "8081:80"
    restart: unless-stopped
    volumes:
      - ./d_modules:/var/www/html/modules \
      - ./d_profiles:/var/www/html/profiles \
      - ./d_sites:/var/www/html/sites \
      - ./d_themes:/var/www/html/themes \
    depends_on:
      - drupal_db
    environment:
      HOST: drupal_db:33061
      DBASE: drupal
      USER: drupal
      PASS: drupal
      DATABASE_HOST: drupal_db:33061
    links:
      - drupal_db:mysql

  drupal_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: drupal_db
    ports:
      - "33061:3306"
    restart: unless-stopped
    volumes:
      - drupal_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

volumes:
  wordpress_db_data: {}
  drupal_db_data: {}
  wordpress_data: {}
  drupal_data: {}

networks:
  wordpress:
  drupal: